MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 1000
DATASETS:
  TRAIN: ("ead_2019_release1_soft_whole_train", "ead_2019_release2_soft_whole_train") #, "ead_2019_detection_val_01", "ead_2019_detection_val_02"
  TEST: ("ead_2019_release1_soft_whole_val", "ead_2019_release2_soft_whole_val")
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (120000, 160000)
  MAX_ITER: 180000
  IMS_PER_BATCH: 8
